import { Product, CareerPost, Update, Service, ProductCategory } from '../types';

// ─────────────────────────────────────────────────────────────────
// PRODUCTS  –  to replace placeholder images, put your own image
// path in `imageUrl` (e.g. '/images/mould1.jpg' after uploading
// to frontend/public/images/) and update the `gallery` array too.
// ─────────────────────────────────────────────────────────────────
export const MOCK_PRODUCTS_DB: Product[] = [

  // ── MOULDS (16 Real Industrial Mould Photos) ───────────────────
  {
    _id: 'm1',
    name: '8-Cavity Precision Slide Injection Mould',
    category: 'Mould',
    description: 'High-precision multi-cavity injection mould tooling on white background.',
    imageUrl: '/images/mould1.jpg',
    gallery: ['/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-01'),
  },
  {
    _id: 'm2',
    name: '2-Cavity Precision Slide-Action Mould Halves',
    category: 'Mould',
    description: 'Side-by-side core and cavity precision injection tool on studio white background.',
    imageUrl: '/images/mould2.jpg',
    gallery: ['/images/mould2.jpg', '/images/mould1.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-02'),
  },
  {
    _id: 'm3',
    name: 'Multi-Cavity Bottle Closure & Cap Mould with Mastip Hot Runner',
    category: 'Mould',
    description: 'High-cavitation closure mould featuring purple Mastip hot-runner manifold system.',
    imageUrl: '/images/mould3.jpg',
    gallery: ['/images/mould3.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-03'),
  },
  {
    _id: 'm4',
    name: '16-Cavity Closure Mould with Blue Heater Connector Box',
    category: 'Mould',
    description: 'Multi-plate precision closure mould with blue electrical junction box on pure white background.',
    imageUrl: '/images/mould4.jpg',
    gallery: ['/images/mould4.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-04'),
  },
  {
    _id: 'm5',
    name: 'Heavy-Duty Injection Mould Block with Dual Red Handles',
    category: 'Mould',
    description: 'Precision industrial mould tool with twin red lifting handles on studio white background.',
    imageUrl: '/images/mould5.jpg',
    gallery: ['/images/mould5.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-05'),
  },
  {
    _id: 'm6',
    name: 'Precision Tubular Core Pin & Slide Mechanism Tool Base',
    category: 'Mould',
    description: 'Industrial mould tool assembly with core pin, slide mechanism, and frame plate details.',
    imageUrl: '/images/mould6.jpg',
    gallery: ['/images/mould6.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-06'),
  },
  {
    _id: 'm7',
    name: 'Mastip Hot-Runner System Injection Mould Assembly',
    category: 'Mould',
    description: 'Precision hot-runner injection mould featuring top Mastip manifold.',
    imageUrl: '/images/mould7.jpg',
    gallery: ['/images/mould7.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-07'),
  },
  {
    _id: 'm8',
    name: 'High-Precision Dome Cavity Mould with Spherical Cores & Bolts',
    category: 'Mould',
    description: 'Specialized dome moulding tool with hardware bolts and polished sphere cores.',
    imageUrl: '/images/mould8.jpg',
    gallery: ['/images/mould8.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-08'),
  },
  {
    _id: 'm9',
    name: 'Multi-Pin Vertical Mastip Injection Mould Plate',
    category: 'Mould',
    description: 'Vertical orientation multi-pin precision injection plate with Mastip header.',
    imageUrl: '/images/mould9.jpg',
    gallery: ['/images/mould9.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-09'),
  },
  {
    _id: 'm10',
    name: 'Multi-Slide High-Cavitation Industrial Mould',
    category: 'Mould',
    description: 'Robotic cell precision injection mould tool.',
    imageUrl: '/images/mould10.jpg',
    gallery: ['/images/mould10.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-10'),
  },
  {
    _id: 'm11',
    name: '16-Cavity High-Efficiency Closure Tooling',
    category: 'Mould',
    description: 'High-density cavitation closure mould with top electrical manifold box.',
    imageUrl: '/images/mould11.jpg',
    gallery: ['/images/mould11.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-11'),
  },
  {
    _id: 'm12',
    name: 'Dual-Cavity Slide Mechanism Core Plate',
    category: 'Mould',
    description: 'Hardened tool steel dual-cavity slide injection block.',
    imageUrl: '/images/mould12.jpg',
    gallery: ['/images/mould12.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-12'),
  },
  {
    _id: 'm13',
    name: 'Precision Slide Mechanism & Guide Pin Assembly',
    category: 'Mould',
    description: 'Tubular core pin and hardened guide pin precision assembly breakdown.',
    imageUrl: '/images/mould13.jpg',
    gallery: ['/images/mould13.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould14.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-13'),
  },
  {
    _id: 'm14',
    name: 'High-Precision Dome Moulding Tool Base',
    category: 'Mould',
    description: 'Dome-shaped cavity moulding block with sphere cores and mounting hardware.',
    imageUrl: '/images/mould14.jpg',
    gallery: ['/images/mould14.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould15.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-14'),
  },
  {
    _id: 'm15',
    name: 'Vertical Mastip Multi-Pin Closure Mould',
    category: 'Mould',
    description: 'Vertical pin-array closure mould with Mastip hot runner control unit.',
    imageUrl: '/images/mould15.jpg',
    gallery: ['/images/mould15.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould16.jpg'],
    updatedAt: new Date('2024-10-15'),
  },
  {
    _id: 'm16',
    name: 'Heavy Industrial Mould Block with Red Handles',
    category: 'Mould',
    description: 'Studio white background heavy-duty mould tool with red positioning handles.',
    imageUrl: '/images/mould16.jpg',
    gallery: ['/images/mould16.jpg', '/images/mould1.jpg', '/images/mould2.jpg', '/images/mould3.jpg', '/images/mould4.jpg', '/images/mould5.jpg', '/images/mould6.jpg', '/images/mould7.jpg', '/images/mould8.jpg', '/images/mould9.jpg', '/images/mould10.jpg', '/images/mould11.jpg', '/images/mould12.jpg', '/images/mould13.jpg', '/images/mould14.jpg', '/images/mould15.jpg'],
    updatedAt: new Date('2024-10-16'),
  },

  // ── MACHINERY: CNC ─────────────────────────────────────────────
  {
    _id: '4',
    name: 'AMS MCV-400 CNC Machine',
    category: 'CNC',
    description: 'High-precision milling, mold cavity detailing, electrode manufacturing, and small-to-medium component batch production.',
    imageUrl: '/images/placeholder-machine.svg',
    gallery: [],
    updatedAt: new Date('2023-01-10'),
  },
  {
    _id: '7',
    name: 'COSMOS CVM-1060 CNC Machine',
    category: 'CNC',
    description: 'Large mold bases, deep cavity core/cavity machining, heavy metal removal, and large industrial plastic/die-casting tool blocks.',
    imageUrl: '/images/placeholder-machine.svg',
    gallery: [],
    updatedAt: new Date('2022-11-20'),
  },

  // ── MACHINERY: EDM ─────────────────────────────────────────────
  {
  _id: '9',
  name: 'Electronica ZNC',
  category: 'EDM',
  description: 'Precision EDM for complex cavities and fine finishes.',
  imageUrl: '/images/placeholder-machine.svg',
  gallery: [],
  updatedAt: new Date('2024-10-22'),
},
{
  _id: '10',
  name: 'Sparkronix-ZNC',
  category: 'EDM',
  description: 'High-precision EDM for intricate details and mould tooling.',
  imageUrl: '/images/placeholder-machine.svg',
  gallery: [],
  updatedAt: new Date('2023-05-18'),
},

  // ── END COMPONENTS (38 Cropped Plastic Components) ───────────────
  { _id: 'ec1', name: 'Plastic Component 1', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_1.jpg', gallery: ['/images/comp_item_1.jpg'], updatedAt: new Date('2024-10-01') },
  { _id: 'ec2', name: 'Plastic Component 2', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_2.jpg', gallery: ['/images/comp_item_2.jpg'], updatedAt: new Date('2024-10-02') },
  { _id: 'ec3', name: 'Plastic Component 3', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_3.jpg', gallery: ['/images/comp_item_3.jpg'], updatedAt: new Date('2024-10-03') },
  { _id: 'ec4', name: 'Plastic Component 4', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_4.jpg', gallery: ['/images/comp_item_4.jpg'], updatedAt: new Date('2024-10-04') },
  { _id: 'ec5', name: 'Plastic Component 5', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_5.jpg', gallery: ['/images/comp_item_5.jpg'], updatedAt: new Date('2024-10-05') },
  { _id: 'ec6', name: 'Plastic Component 6', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_6.jpg', gallery: ['/images/comp_item_6.jpg'], updatedAt: new Date('2024-10-06') },
  { _id: 'ec7', name: 'Plastic Component 7', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_7.jpg', gallery: ['/images/comp_item_7.jpg'], updatedAt: new Date('2024-10-07') },
  { _id: 'ec8', name: 'Plastic Component 8', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_8.jpg', gallery: ['/images/comp_item_8.jpg'], updatedAt: new Date('2024-10-08') },
  { _id: 'ec9', name: 'Plastic Component 9', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_9.jpg', gallery: ['/images/comp_item_9.jpg'], updatedAt: new Date('2024-10-09') },
  { _id: 'ec10', name: 'Plastic Component 10', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_10.jpg', gallery: ['/images/comp_item_10.jpg'], updatedAt: new Date('2024-10-10') },
  { _id: 'ec11', name: 'Plastic Component 11', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_11.jpg', gallery: ['/images/comp_item_11.jpg'], updatedAt: new Date('2024-10-11') },
  { _id: 'ec12', name: 'Plastic Component 12', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_12.jpg', gallery: ['/images/comp_item_12.jpg'], updatedAt: new Date('2024-10-12') },
  { _id: 'ec13', name: 'Plastic Component 13', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_13.jpg', gallery: ['/images/comp_item_13.jpg'], updatedAt: new Date('2024-10-13') },
  { _id: 'ec14', name: 'Plastic Component 14', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_14.jpg', gallery: ['/images/comp_item_14.jpg'], updatedAt: new Date('2024-10-14') },
  { _id: 'ec15', name: 'Plastic Component 15', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_15.jpg', gallery: ['/images/comp_item_15.jpg'], updatedAt: new Date('2024-10-15') },
  { _id: 'ec16', name: 'Plastic Component 16', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_16.jpg', gallery: ['/images/comp_item_16.jpg'], updatedAt: new Date('2024-10-16') },
  { _id: 'ec17', name: 'Plastic Component 17', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_17.jpg', gallery: ['/images/comp_item_17.jpg'], updatedAt: new Date('2024-10-17') },
  { _id: 'ec18', name: 'Plastic Component 18', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_18.jpg', gallery: ['/images/comp_item_18.jpg'], updatedAt: new Date('2024-10-18') },
  { _id: 'ec19', name: 'Plastic Component 19', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_19.jpg', gallery: ['/images/comp_item_19.jpg'], updatedAt: new Date('2024-10-19') },
  { _id: 'ec20', name: 'Plastic Component 20', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_20.jpg', gallery: ['/images/comp_item_20.jpg'], updatedAt: new Date('2024-10-20') },
  { _id: 'ec21', name: 'Plastic Component 21', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_21.jpg', gallery: ['/images/comp_item_21.jpg'], updatedAt: new Date('2024-10-21') },
  { _id: 'ec22', name: 'Plastic Component 22', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_22.jpg', gallery: ['/images/comp_item_22.jpg'], updatedAt: new Date('2024-10-22') },
  { _id: 'ec23', name: 'Plastic Component 23', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_23.jpg', gallery: ['/images/comp_item_23.jpg'], updatedAt: new Date('2024-10-23') },
  { _id: 'ec24', name: 'Plastic Component 24', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_24.jpg', gallery: ['/images/comp_item_24.jpg'], updatedAt: new Date('2024-10-24') },
  { _id: 'ec25', name: 'Plastic Component 25', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_25.jpg', gallery: ['/images/comp_item_25.jpg'], updatedAt: new Date('2024-10-25') },
  { _id: 'ec26', name: 'Plastic Component 26', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_26.jpg', gallery: ['/images/comp_item_26.jpg'], updatedAt: new Date('2024-10-26') },
  { _id: 'ec27', name: 'Plastic Component 27', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_27.jpg', gallery: ['/images/comp_item_27.jpg'], updatedAt: new Date('2024-10-27') },
  { _id: 'ec28', name: 'Plastic Component 28', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_28.jpg', gallery: ['/images/comp_item_28.jpg'], updatedAt: new Date('2024-10-28') },
  { _id: 'ec29', name: 'Plastic Component 29', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_29.jpg', gallery: ['/images/comp_item_29.jpg'], updatedAt: new Date('2024-10-29') },
  { _id: 'ec30', name: 'Plastic Component 30', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_30.jpg', gallery: ['/images/comp_item_30.jpg'], updatedAt: new Date('2024-10-30') },
  { _id: 'ec31', name: 'Plastic Component 31', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_31.jpg', gallery: ['/images/comp_item_31.jpg'], updatedAt: new Date('2024-10-31') },
  { _id: 'ec32', name: 'Plastic Component 32', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_32.jpg', gallery: ['/images/comp_item_32.jpg'], updatedAt: new Date('2024-11-01') },
  { _id: 'ec33', name: 'Plastic Component 33', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_33.jpg', gallery: ['/images/comp_item_33.jpg'], updatedAt: new Date('2024-11-02') },
  { _id: 'ec34', name: 'Plastic Component 34', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_34.jpg', gallery: ['/images/comp_item_34.jpg'], updatedAt: new Date('2024-11-03') },
  { _id: 'ec35', name: 'Plastic Component 35', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_35.jpg', gallery: ['/images/comp_item_35.jpg'], updatedAt: new Date('2024-11-04') },
  { _id: 'ec36', name: 'Plastic Component 36', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_36.jpg', gallery: ['/images/comp_item_36.jpg'], updatedAt: new Date('2024-11-05') },
  { _id: 'ec37', name: 'Plastic Component 37', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_37.jpg', gallery: ['/images/comp_item_37.jpg'], updatedAt: new Date('2024-11-06') },
  { _id: 'ec38', name: 'Plastic Component 38', category: 'End Component', description: 'Precision injection moulded plastic component.', imageUrl: '/images/comp_item_38.jpg', gallery: ['/images/comp_item_38.jpg'], updatedAt: new Date('2024-11-07') },
];

// ─────────────────────────────────────────────────────────────────
// CAREERS  –  edit positions/descriptions here, or manage via API
// ─────────────────────────────────────────────────────────────────
export const MOCK_CAREERS_DB: CareerPost[] = [
  {
    _id: 'c1',
    position: 'CNC Operator',
    description: 'We are looking for an experienced CNC Operator.',
    location: 'Hyderabad, India',
  },
  {
    _id: 'c2',
    position: 'Mould Designer',
    description: 'Seeking a creative and technical Mould Designer with 5+ years of experience in SolidWorks or a similar CAD program for complex injection moulds.',
    location: 'Hyderabad, India',
  },
  {
    _id: 'c3',
    position: 'CNC Operator Trainee',
    description: 'Looking for a fresher to work as a CNC Operator Trainee.',
    location: 'Hyderabad, India',
  },
  {
    _id: 'c4',
    position: 'Designer Trainee',
    description: 'Looking for a fresher to work as a Designer Trainee.',
    location: 'Hyderabad, India',
  },
];

export const MOCK_UPDATES_DB: Update[] = [
  { _id: 'u1', title: 'New High-Strength Polymer Acquired', description: 'We are now using PEEK polymer for high-temperature applications, enhancing component durability.', date: '2024-10-26' },
  { _id: 'u2', title: '5-Axis CNC Machine Added to Workshop', description: 'Our new 5-axis CNC machine allows for more complex geometries and faster production times.', date: '2024-10-22' },
  { _id: 'u3', title: 'Expanded capacity for pharma moulds', description: 'We have successfully expanded our cleanroom facilities to meet the growing demand for medical and pharma-grade moulds.', date: '2024-10-15' },
];

export const MOCK_SERVICES_DB: Service[] = [
  {
    _id: 's1',
    title: 'Mould Design & Prototyping',
    description: 'From concept to reality, we provide comprehensive 3D mould design and rapid prototyping services to validate your components before mass production.',
    icon: 'LightBulbIcon',
  },
  {
    _id: 's2',
    title: 'High-Precision CNC Machining',
    description: 'Utilizing our state-of-the-art CNC mills and EDM machines, we craft complex mould cavities and cores with sub-micron accuracy.',
    icon: 'WrenchScrewdriverIcon',
  },
  {
    _id: 's3',
    title: '2K & 3K Injection Moulding',
    description: 'Specializing in multi-material moulds (2K & 3K), we enable the creation of sophisticated parts with integrated soft-touch grips, seals, or multiple colors.',
    icon: 'CubeTransparentIcon',
  },
  {
    _id: 's4',
    title: 'Mould Maintenance & Repair',
    description: 'We offer comprehensive maintenance and repair services to extend the life of your tooling, ensuring consistent quality and performance over millions of cycles.',
    icon: 'ShieldCheckIcon',
  },
];
